#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Wed Sep 20 15:21:07 CEST 2017
apiSecret=f3f6129e7c561af6bc9d793b2875a3cb15151518dc31e8d221624c51967e9a81
